# Generated by Django 3.2.12 on 2022-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_auto_20220728_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Bank',
            field=models.TextField(choices=[('SBI', 'SBI'), ('PNB', 'PNB'), ('Axis', 'Axis')], default='SBI', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology Engineering', 'Information Technology Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Electronics Engineering', 'Electronics Engineering')], max_length=200),
        ),
    ]
