# Generated by Django 3.2.12 on 2022-07-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_auto_20220728_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_Status',
            field=models.BooleanField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='Bank',
            field=models.BooleanField(choices=[('SBI', 'SBI'), ('PNB', 'PNB'), ('Axis', 'Axis')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
