# Generated by Django 3.2.12 on 2022-07-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0027_auto_20220729_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_Status',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='Bank',
            field=models.TextField(choices=[('SBI', 'SBI'), ('PNB', 'PNB'), ('Axis', 'Axis')], default=' ', max_length=100),
        ),
    ]
