# Generated by Django 3.2.12 on 2022-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0029_auto_20220801_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Capital_Amount',
            field=models.IntegerField(null=True),
        ),
    ]
