# Generated by Django 3.2.12 on 2022-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_auto_20220801_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gRE_Score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='iELTS_Score',
            field=models.IntegerField(null=True),
        ),
    ]
