# Generated by Django 3.2.12 on 2022-08-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0035_auto_20220807_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='message',
            new_name='Axis_Message',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Application_Status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Capital_Amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Interest',
        ),
        migrations.AddField(
            model_name='application',
            name='Axis_Capital_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Axis_Interest',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Axis_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='HDFC_Capital_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='HDFC_Interest',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='HDFC_Message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='HDFC_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='PNB_Capital_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='PNB_Interest',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='PNB_Message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='PNB_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='SBI_Capital_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='SBI_Interest',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='SBI_Message',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='SBI_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
