# Generated by Django 3.2.12 on 2022-08-08 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0037_auto_20220808_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bank',
            field=models.TextField(choices=[('State Bank of India', 'State Bank of India'), ('Punjab National Bank', 'Punjab National Bank'), ('Axis Bank', 'Axis Bank'), ('HDFC Bank', 'HDFC Bank')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
