# Generated by Django 3.2.12 on 2022-08-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0041_auto_20220809_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Axis_Capital_Amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Axis_Interest',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.0', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Axis_Message',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='HDFC_Capital_Amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='HDFC_Interest',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.0', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='HDFC_Message',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='PNB_Capital_Amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='PNB_Interest',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.0', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='PNB_Message',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='SBI_Capital_Amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='SBI_Interest',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.0', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='SBI_Message',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
