# Generated by Django 3.2.12 on 2022-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0042_auto_20220809_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Axis_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='HDFC_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='PNB_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='SBI_Status',
            field=models.TextField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
    ]
